# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('add_inline', models.BooleanField(default=False, help_text='Tick this!')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads')),
                ('clearable_file_upload', models.FileField(blank=True, upload_to='uploads')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_models.Demo')),
            ],
        ),
        migrations.CreateModel(
            name='ManySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='demo',
            name='filter_horizontal',
            field=models.ManyToManyField(blank=True, related_name='_demo_filter_horizontal_+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='filter_vertical',
            field=models.ManyToManyField(blank=True, related_name='_demo_filter_vertical_+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='many_to_many',
            field=models.ManyToManyField(blank=True, related_name='_demo_many_to_many_+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='radio_fields_horizontal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='radio_fields_vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='raw_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='demo',
            name='raw_many_to_many',
            field=models.ManyToManyField(blank=True, related_name='_demo_raw_many_to_many_+', to='demo_models.ManySource'),
        ),
        migrations.AddField(
            model_name='dateinline',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_models.Demo'),
        ),
    ]
